// Rich XLSX assembler for the screen reports: one worksheet per chart holding
// that chart's underlying data. Styling mirrors the design-foundations header
// treatment already used by src/lib/exports/xlsx.ts (Moon Raker header fill,
// frozen first row) without importing/altering that module.
import ExcelJS from 'exceljs';
import type { ChartDatum, ScreenData } from '../data/live-queries';
import type { ScreenSpec } from '../screen-specs';

const HEADER_FILL: ExcelJS.Fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1C4854' } };
const HEADER_FONT: Partial<ExcelJS.Font> = { name: 'Calibri', bold: true, color: { argb: 'FFFFFFFF' }, size: 11 };

export type RichXlsxInput = {
  spec: ScreenSpec;
  data: ScreenData;
  title: string;
  generatedBy: string;
  generatedAt?: string;
  chartTitles: Record<string, string>;
};

// Excel sheet names: ≤31 chars, no []:*?/\ — keep them unique per chart id.
function sheetName(id: string, used: Set<string>): string {
  let base = id.replace(/[\[\]:*?/\\]/g, ' ').slice(0, 28);
  let name = base || 'Sheet';
  let n = 1;
  while (used.has(name.toLowerCase())) name = `${base.slice(0, 25)} ${++n}`;
  used.add(name.toLowerCase());
  return name;
}

function writeDatum(ws: ExcelJS.Worksheet, datum: ChartDatum) {
  let headers: string[] = [];
  const rows: Array<Array<string | number>> = [];
  switch (datum.kind) {
    case 'categorical':
      headers = ['Category', 'Value'];
      datum.labels.forEach((l, i) => rows.push([l, datum.values[i] ?? 0]));
      break;
    case 'multi':
      headers = ['Category', ...datum.series.map((s) => s.name || 'Series')];
      datum.labels.forEach((l, i) => rows.push([l, ...datum.series.map((s) => s.values[i] ?? 0)]));
      break;
    case 'points':
      headers = ['X', 'Y'];
      datum.points.forEach((p) => rows.push([p.x, p.y]));
      break;
    case 'matrix':
      headers = ['', ...datum.xLabels];
      datum.matrix.forEach((r, i) => rows.push([datum.yLabels[i] ?? String(i), ...r]));
      break;
    case 'values':
      headers = ['Index', 'Value'];
      datum.values.forEach((v, i) => rows.push([i, v]));
      break;
  }
  ws.addRow(headers);
  const header = ws.getRow(1);
  header.eachCell((cell) => {
    cell.fill = HEADER_FILL;
    cell.font = HEADER_FONT;
  });
  header.height = 20;
  ws.views = [{ state: 'frozen', ySplit: 1 }];
  for (const r of rows) ws.addRow(r);
  ws.columns.forEach((col) => {
    col.width = 22;
  });
}

export async function renderRichXlsx(input: RichXlsxInput): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = input.generatedBy;
  wb.created = new Date(input.generatedAt ?? Date.now());
  wb.title = input.title;

  const used = new Set<string>();
  // Cover / index sheet.
  const cover = wb.addWorksheet(sheetName('Overview', used));
  cover.addRow([input.title]);
  cover.getRow(1).font = { name: 'Calibri', bold: true, size: 16, color: { argb: 'FF1C4854' } };
  cover.addRow([`Generated by ${input.generatedBy} · ${new Date(input.generatedAt ?? Date.now()).toISOString().slice(0, 16).replace('T', ' ')} UTC`]);
  cover.addRow([]);
  cover.addRow(['Chart', 'Sheet']);

  for (const spec of input.spec.charts) {
    const datum = input.data[spec.dataKey];
    if (!datum) continue;
    const name = sheetName(spec.id, used);
    const ws = wb.addWorksheet(name);
    writeDatum(ws, datum);
    cover.addRow([input.chartTitles[spec.id] ?? spec.id, name]);
  }

  const buf = await wb.xlsx.writeBuffer();
  return Buffer.from(buf);
}
