// Shared design-foundations tokens and helpers for all generated exports
// (XLSX / PDF / DOCX). Keeping them in one place guarantees the three export
// formats stay visually consistent and on-brand.

// Design-foundations palette. Hex without the leading '#' variants are provided
// because exceljs ARGB colours want an 8-char string and pdf-lib wants 0-1 rgb.
export const BRAND = {
  primary: '01696F',
  text: '28251D',
  muted: '7A7974',
  error: 'A12C7B',
  white: 'FFFFFF',
} as const;

// exceljs fills expect ARGB (alpha first).
export const argb = (hex: string) => `FF${hex}`.toUpperCase();

// pdf-lib wants normalised 0-1 channels.
export function rgb01(hex: string): [number, number, number] {
  const n = hex.replace('#', '');
  return [
    parseInt(n.slice(0, 2), 16) / 255,
    parseInt(n.slice(2, 4), 16) / 255,
    parseInt(n.slice(4, 6), 16) / 255,
  ];
}

// Fonts used across formats.
export const FONT_LATIN = 'Calibri'; // XLSX / DOCX
export const FONT_ARABIC = 'IBM Plex Sans Arabic'; // PDF (embedded) / DOCX

// Thousand-separated integer, locale-aware. Kept ASCII digits for en so
// spreadsheets treat exported text columns predictably; ar uses Arabic-Indic
// only in display strings, never in numeric cells.
export function fmtInt(value: number, locale = 'en'): string {
  return new Intl.NumberFormat(locale === 'ar' ? 'ar-SA' : 'en-US', {
    maximumFractionDigits: 0,
  }).format(value);
}

export function fmtDecimal(value: number, locale = 'en', digits = 1): string {
  return new Intl.NumberFormat(locale === 'ar' ? 'ar-SA' : 'en-US', {
    minimumFractionDigits: digits,
    maximumFractionDigits: digits,
  }).format(value);
}

// A generation footer line embedded (as text or metadata) in every export so a
// printed/shared copy is always traceable to who produced it and when.
export function generationFooter(
  generatedBy: string,
  locale = 'en',
  now = new Date()
): string {
  const stamp = now.toISOString().replace('T', ' ').slice(0, 16) + ' UTC';
  return locale === 'ar'
    ? `أُنشئ بواسطة ${generatedBy} · ${stamp}`
    : `Generated by ${generatedBy} · ${stamp}`;
}

// Insight-stating title, e.g. "Ideas — 47 total, 12 approved".
export function insightTitle(
  base: string,
  parts: Array<{ label: string; count: number }>,
  locale = 'en'
): string {
  const seg = parts.map((p) => `${fmtInt(p.count, locale)} ${p.label}`).join(', ');
  return seg ? `${base} — ${seg}` : base;
}
