// Rich, chart-driven PPTX renderer for the 18 screen reports.
//   • Slide 1: cover (title, subtitle, generated_at, filters)
//   • Slides 2..N: one chart per slide (chart rendered to PNG, embedded)
//   • Final slide: KPI summary (totals derived from the categorical datasets)
//
// PPTX cannot embed custom fonts, so chrome text uses a system font; the chart
// imagery carries the branded palette from renderChart.
import PptxGenJS from 'pptxgenjs';
import { renderSpecChart } from '../charts/render-spec';
import type { ChartDatum, ScreenData } from '../data/live-queries';
import type { ScreenSpec } from '../screen-specs';

const PRIMARY = '1C4854'; // Moon Raker
const SWANS = 'D8EFE5';
const TEXT = '232529';
const MUTED = '5C5F66';
const WHITE = 'FFFFFF';
const FONT = 'Calibri';

const SLIDE_W = 13.333;
const SLIDE_H = 7.5;

export type RichPptxInput = {
  screenId: string;
  spec: ScreenSpec;
  data: ScreenData;
  locale: 'ar' | 'en';
  title: string;
  subtitle?: string;
  generatedBy: string;
  generatedAt?: string;
  filters?: string;
  chartTitles: Record<string, string>;
};

function pngDataUrl(buf: Buffer): string {
  return `data:image/png;base64,${buf.toString('base64')}`;
}

function sumDatum(d: ChartDatum | undefined): number {
  if (!d) return 0;
  if (d.kind === 'categorical') return d.values.reduce((a, b) => a + b, 0);
  if (d.kind === 'values') return d.values.reduce((a, b) => a + b, 0);
  if (d.kind === 'multi') return d.series.reduce((a, s) => a + s.values.reduce((x, y) => x + y, 0), 0);
  if (d.kind === 'points') return d.points.length;
  return 0;
}

export async function renderRichPptx(input: RichPptxInput): Promise<Buffer> {
  const pptx = new PptxGenJS();
  pptx.defineLayout({ name: 'I2I', width: SLIDE_W, height: SLIDE_H });
  pptx.layout = 'I2I';
  pptx.author = 'Innovation to Impact';
  pptx.title = input.title;
  const rtl = input.locale === 'ar';
  const align: 'right' | 'left' = rtl ? 'right' : 'left';
  const generatedAt = input.generatedAt ?? new Date().toISOString();

  // ── Cover ─────────────────────────────────────────────────────────────────
  const cover = pptx.addSlide();
  cover.background = { color: PRIMARY };
  cover.addShape('rect', { x: 0, y: 0, w: SLIDE_W, h: 0.12, fill: { color: SWANS } });
  cover.addText(input.title, {
    x: 0.7,
    y: 2.4,
    w: SLIDE_W - 1.4,
    h: 1.4,
    fontSize: 40,
    bold: true,
    fontFace: FONT,
    color: WHITE,
    align,
  });
  if (input.subtitle)
    cover.addText(input.subtitle, { x: 0.7, y: 3.9, w: SLIDE_W - 1.4, h: 0.8, fontSize: 16, fontFace: FONT, color: SWANS, align });
  const stamp = new Date(generatedAt).toISOString().replace('T', ' ').slice(0, 16) + ' UTC';
  const metaBits = [
    (rtl ? 'أُنشئ بواسطة ' : 'Generated by ') + input.generatedBy + ' · ' + stamp,
    input.filters ? (rtl ? 'المرشّحات: ' : 'Filters: ') + input.filters : '',
  ].filter(Boolean);
  cover.addText(metaBits.join('\n'), { x: 0.7, y: 5.3, w: SLIDE_W - 1.4, h: 0.8, fontSize: 12, fontFace: FONT, color: SWANS, align });

  // ── One slide per chart ─────────────────────────────────────────────────────
  for (const spec of input.spec.charts) {
    const s = pptx.addSlide();
    s.background = { color: WHITE };
    s.addShape('rect', { x: 0, y: 0, w: SLIDE_W, h: 0.9, fill: { color: PRIMARY } });
    s.addText(input.chartTitles[spec.id] ?? spec.id, {
      x: 0.6,
      y: 0.12,
      w: SLIDE_W - 1.2,
      h: 0.66,
      fontSize: 22,
      bold: true,
      fontFace: FONT,
      color: WHITE,
      align,
    });
    const png = renderSpecChart(spec, input.data[spec.dataKey], { width: 1120, height: 560 });
    // Fit inside the content area preserving 2:1 aspect.
    const boxW = SLIDE_W - 1.6;
    const boxH = boxW / 2;
    const w = Math.min(boxW, (SLIDE_H - 1.6) * 2);
    const h = w / 2;
    s.addImage({ data: pngDataUrl(png), x: (SLIDE_W - w) / 2, y: 1.1, w, h });
    void boxH;
  }

  // ── KPI summary (last slide) ────────────────────────────────────────────────
  const kpiSlide = pptx.addSlide();
  kpiSlide.background = { color: SWANS };
  kpiSlide.addText(rtl ? 'ملخّص المؤشرات' : 'KPI Summary', {
    x: 0.6,
    y: 0.4,
    w: SLIDE_W - 1.2,
    h: 0.7,
    fontSize: 28,
    bold: true,
    fontFace: FONT,
    color: TEXT,
    align,
  });
  const kpiSpecs = input.spec.charts
    .map((spec) => ({ label: input.chartTitles[spec.id] ?? spec.id, value: sumDatum(input.data[spec.dataKey]) }))
    .filter((k) => k.value > 0)
    .slice(0, 6);
  const cols = 3;
  const cardW = (SLIDE_W - 1.2 - 0.4 * (cols - 1)) / cols;
  const cardH = 1.7;
  kpiSpecs.forEach((kpi, i) => {
    const col = i % cols;
    const row = Math.floor(i / cols);
    const x = 0.6 + col * (cardW + 0.4);
    const y = 1.4 + row * (cardH + 0.4);
    kpiSlide.addShape('rect', { x, y, w: cardW, h: cardH, fill: { color: WHITE }, line: { color: PRIMARY, width: 0.75 } });
    kpiSlide.addText(String(kpi.value), { x: x + 0.2, y: y + 0.3, w: cardW - 0.4, h: 0.8, fontSize: 40, bold: true, fontFace: FONT, color: PRIMARY, align });
    kpiSlide.addText(kpi.label, { x: x + 0.2, y: y + 1.05, w: cardW - 0.4, h: 0.5, fontSize: 12, fontFace: FONT, color: MUTED, align });
  });

  const out = (await pptx.write({ outputType: 'nodebuffer' })) as Buffer;
  return out;
}
