// Generic XLSX renderer. One sheet per ReportSection + a "Summary" sheet with
// KPIs at the top. Uses exceljs so we stay consistent with existing exports.
import ExcelJS from 'exceljs';
import type { ReportBundle } from './types';
import { REPORT_META } from './types';

const BRAND_PRIMARY = 'FF01696F';
const BRAND_SURFACE = 'FFF7F6F2';
const BRAND_TEXT = 'FF28251D';
const BRAND_MUTED = 'FF7A7974';
const FONT = 'Calibri';

function headerStyle(cell: ExcelJS.Cell) {
  cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: BRAND_PRIMARY } };
  cell.font = { name: FONT, bold: true, color: { argb: 'FFFFFFFF' }, size: 11 };
  cell.alignment = { vertical: 'middle', horizontal: 'left' };
}

function safeSheetName(name: string, taken: Set<string>): string {
  // Excel disallows [ ] * ? / \ : and max 31 chars.
  let clean = name.replace(/[\[\]\*\?\/\\:]/g, ' ').slice(0, 31).trim() || 'Sheet';
  let n = 1;
  const base = clean;
  while (taken.has(clean.toLowerCase())) {
    const suffix = ` (${++n})`;
    clean = (base.slice(0, 31 - suffix.length) + suffix);
  }
  taken.add(clean.toLowerCase());
  return clean;
}

export async function renderXlsx(
  bundle: ReportBundle,
  locale: 'ar' | 'en' = 'en'
): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'Innovation-to-Impact Platform';
  wb.created = new Date();
  wb.title = REPORT_META[bundle.type].name_en;

  const takenNames = new Set<string>();

  // Summary sheet: metadata + KPIs.
  const summary = wb.addWorksheet(safeSheetName(locale === 'ar' ? 'الملخص' : 'Summary', takenNames), {
    views: [{ rightToLeft: locale === 'ar' }],
  });
  summary.columns = [
    { header: '', key: 'label', width: 34 },
    { header: '', key: 'value', width: 34 },
  ];
  const meta = REPORT_META[bundle.type];
  const titleRow = summary.addRow([locale === 'ar' ? meta.name_ar : meta.name_en]);
  summary.mergeCells(`A${titleRow.number}:B${titleRow.number}`);
  titleRow.getCell(1).font = { name: FONT, bold: true, size: 18, color: { argb: BRAND_PRIMARY } };
  titleRow.getCell(1).alignment = { vertical: 'middle', horizontal: 'left' };
  titleRow.height = 28;

  const rangeStr = bundle.dateFrom || bundle.dateTo ? `${bundle.dateFrom ?? '…'} → ${bundle.dateTo ?? '…'}` : locale === 'ar' ? 'كل الفترات' : 'All time';
  summary.addRow([locale === 'ar' ? 'الفترة الزمنية' : 'Date range', rangeStr]);
  summary.addRow([locale === 'ar' ? 'أُنشئ بواسطة' : 'Generated by', bundle.generatedBy]);
  summary.addRow([locale === 'ar' ? 'تاريخ الإنشاء' : 'Generated at', new Date(bundle.generatedAt).toISOString().replace('T', ' ').slice(0, 16) + ' UTC']);
  summary.addRow([]);
  const kpiHeader = summary.addRow([locale === 'ar' ? 'المؤشر' : 'KPI', locale === 'ar' ? 'القيمة' : 'Value']);
  headerStyle(kpiHeader.getCell(1));
  headerStyle(kpiHeader.getCell(2));
  for (const kpi of bundle.kpis) {
    const r = summary.addRow([locale === 'ar' ? kpi.label_ar : kpi.label_en, kpi.value]);
    r.getCell(1).font = { name: FONT, size: 11, color: { argb: BRAND_TEXT } };
    r.getCell(2).font = { name: FONT, size: 11, bold: true, color: { argb: BRAND_PRIMARY } };
  }
  summary.getColumn(1).alignment = { vertical: 'middle', horizontal: 'left' };
  summary.getColumn(2).alignment = { vertical: 'middle', horizontal: 'left' };

  // One sheet per section.
  for (const section of bundle.sections) {
    const sheetName = safeSheetName(locale === 'ar' ? section.title_ar : section.title_en, takenNames);
    const ws = wb.addWorksheet(sheetName, {
      views: [{ state: 'frozen', ySplit: 1, rightToLeft: locale === 'ar' }],
    });
    ws.columns = section.columns.map((c) => ({
      header: locale === 'ar' ? c.label_ar : c.label_en,
      key: c.key,
      width: c.width ?? 18,
    }));
    const headerRow = ws.getRow(1);
    headerRow.eachCell((cell) => headerStyle(cell));
    headerRow.height = 22;

    for (const row of section.rows) {
      const added = ws.addRow(row);
      added.eachCell((cell) => {
        cell.font = { name: FONT, size: 10, color: { argb: BRAND_TEXT } };
        cell.alignment = { vertical: 'middle', horizontal: 'left', wrapText: false };
      });
    }
    // Autofilter across the header if there's data.
    if (section.rows.length) {
      ws.autoFilter = {
        from: { row: 1, column: 1 },
        to: { row: 1, column: section.columns.length },
      };
    }
  }

  const arrayBuffer = await wb.xlsx.writeBuffer();
  return Buffer.from(arrayBuffer as ArrayBuffer);
}
