// Generic PPTX renderer. Layout:
//   - Slide 1: Cover (title + range + author)
//   - Slide 2: KPI grid
//   - Slide 3..N: One slide per section with a table (first 15 rows)
//
// PPTX can't embed fonts, so we stick to system fonts (Calibri).
import PptxGenJS from 'pptxgenjs';
import type { ReportBundle } from './types';
import { REPORT_META } from './types';

const PRIMARY = '01696F';
const SURFACE = 'F7F6F2';
const TEXT = '28251D';
const MUTED = '7A7974';
const WHITE = 'FFFFFF';
const FONT = 'Calibri';

const SLIDE_W = 10; // inches (default 10x5.625 for widescreen)
const SLIDE_H = 5.625;

function truncate(text: string, max: number): string {
  if (!text) return '';
  return text.length <= max ? text : text.slice(0, max - 1) + '…';
}

export async function renderPptx(
  bundle: ReportBundle,
  locale: 'ar' | 'en' = 'en'
): Promise<Buffer> {
  const pptx = new PptxGenJS();
  pptx.company = 'Innovation-to-Impact Platform';
  pptx.author = 'Innovation-to-Impact';
  pptx.title = REPORT_META[bundle.type].name_en;
  pptx.layout = 'LAYOUT_WIDE';

  const meta = REPORT_META[bundle.type];
  const title = locale === 'ar' ? meta.name_ar : meta.name_en;
  const subtitle = locale === 'ar' ? meta.desc_ar : meta.desc_en;
  const rtl = locale === 'ar';

  // ─── Cover slide ───────────────────────────────────────────────────────
  const cover = pptx.addSlide();
  cover.background = { color: PRIMARY };
  cover.addText(title, {
    x: 0.6,
    y: 1.6,
    w: SLIDE_W - 1.2,
    h: 1.2,
    fontSize: 44,
    bold: true,
    fontFace: FONT,
    color: WHITE,
    align: rtl ? 'right' : 'left',
  });
  cover.addText(subtitle, {
    x: 0.6,
    y: 2.9,
    w: SLIDE_W - 1.2,
    h: 0.7,
    fontSize: 16,
    fontFace: FONT,
    color: WHITE,
    align: rtl ? 'right' : 'left',
  });
  const rangeStr =
    bundle.dateFrom || bundle.dateTo
      ? `${bundle.dateFrom ?? '…'} → ${bundle.dateTo ?? '…'}`
      : locale === 'ar'
        ? 'كل الفترات'
        : 'All time';
  cover.addText(rangeStr, {
    x: 0.6,
    y: 4.4,
    w: SLIDE_W - 1.2,
    h: 0.4,
    fontSize: 14,
    fontFace: FONT,
    color: WHITE,
    align: rtl ? 'right' : 'left',
  });
  const stamp = new Date(bundle.generatedAt).toISOString().replace('T', ' ').slice(0, 16) + ' UTC';
  cover.addText(
    (locale === 'ar' ? 'أُنشئ بواسطة ' : 'Generated by ') + bundle.generatedBy + ' · ' + stamp,
    {
      x: 0.6,
      y: 4.9,
      w: SLIDE_W - 1.2,
      h: 0.4,
      fontSize: 11,
      fontFace: FONT,
      color: WHITE,
      align: rtl ? 'right' : 'left',
    }
  );

  // ─── KPI slide ─────────────────────────────────────────────────────────
  if (bundle.kpis.length) {
    const s = pptx.addSlide();
    s.background = { color: SURFACE };
    s.addText(locale === 'ar' ? 'المؤشرات الرئيسية' : 'Key Indicators', {
      x: 0.5,
      y: 0.3,
      w: SLIDE_W - 1,
      h: 0.6,
      fontSize: 26,
      bold: true,
      fontFace: FONT,
      color: TEXT,
      align: rtl ? 'right' : 'left',
    });
    const cols = 3;
    const cardW = (SLIDE_W - 1 - 0.3 * (cols - 1)) / cols;
    const cardH = 1.4;
    bundle.kpis.slice(0, 6).forEach((kpi, i) => {
      const col = i % cols;
      const row = Math.floor(i / cols);
      const x = 0.5 + col * (cardW + 0.3);
      const y = 1.2 + row * (cardH + 0.3);
      s.addShape('rect', {
        x,
        y,
        w: cardW,
        h: cardH,
        fill: { color: WHITE },
        line: { color: 'D4D1CA', width: 0.5 },
      });
      s.addText(locale === 'ar' ? kpi.label_ar : kpi.label_en, {
        x: x + 0.15,
        y: y + 0.1,
        w: cardW - 0.3,
        h: 0.4,
        fontSize: 12,
        fontFace: FONT,
        color: MUTED,
        align: rtl ? 'right' : 'left',
      });
      s.addText(kpi.value, {
        x: x + 0.15,
        y: y + 0.55,
        w: cardW - 0.3,
        h: 0.7,
        fontSize: 32,
        bold: true,
        fontFace: FONT,
        color: PRIMARY,
        align: rtl ? 'right' : 'left',
      });
    });
  }

  // ─── Section slides ────────────────────────────────────────────────────
  for (const section of bundle.sections) {
    const s = pptx.addSlide();
    s.background = { color: WHITE };
    const sTitle = locale === 'ar' ? section.title_ar : section.title_en;
    s.addText(sTitle, {
      x: 0.5,
      y: 0.3,
      w: SLIDE_W - 1,
      h: 0.5,
      fontSize: 22,
      bold: true,
      fontFace: FONT,
      color: PRIMARY,
      align: rtl ? 'right' : 'left',
    });

    // Build a table: header row + up to 15 body rows.
    const headerCells = section.columns.map((c) => ({
      text: truncate(locale === 'ar' ? c.label_ar : c.label_en, 28),
      options: {
        bold: true,
        color: WHITE,
        fill: { color: PRIMARY },
        fontFace: FONT,
        fontSize: 11,
        align: (rtl ? 'right' : 'left') as 'right' | 'left',
      },
    }));
    const bodyRows = section.rows.slice(0, 15).map((row) =>
      section.columns.map((c) => ({
        text: truncate(row[c.key] == null ? '' : String(row[c.key]), 60),
        options: {
          color: TEXT,
          fontFace: FONT,
          fontSize: 10,
          align: (rtl ? 'right' : 'left') as 'right' | 'left',
        },
      }))
    );
    const tableRows = [headerCells, ...bodyRows];

    s.addTable(tableRows, {
      x: 0.5,
      y: 0.95,
      w: SLIDE_W - 1,
      colW: section.columns.map((c) => ((c.width ?? 20) / section.columns.reduce((a, cc) => a + (cc.width ?? 20), 0)) * (SLIDE_W - 1)),
      border: { type: 'solid', color: 'D4D1CA', pt: 0.5 },
      fontSize: 10,
      autoPage: false,
    });

    if (section.rows.length > 15) {
      s.addText(
        locale === 'ar'
          ? `و ${section.rows.length - 15} صف إضافي — راجع ملف Excel للتفاصيل الكاملة.`
          : `+ ${section.rows.length - 15} more rows — see Excel export for full data.`,
        {
          x: 0.5,
          y: SLIDE_H - 0.5,
          w: SLIDE_W - 1,
          h: 0.3,
          fontSize: 10,
          italic: true,
          fontFace: FONT,
          color: MUTED,
          align: rtl ? 'right' : 'left',
        }
      );
    }
  }

  const blob = await pptx.write({ outputType: 'nodebuffer' });
  return blob as Buffer;
}
