// Generic PDF renderer for any ReportBundle. Uses pdf-lib + fontkit with an
// embedded Frutiger LT Arabic (aligned with the platform style guide). Arabic
// runs are shaped by fontkit's layout() pass, so the result reads natively.
//
// Layout:
//   1. Cover page — brand block, title, subtitle, reporting period, generated by/on
//   2. Table of Contents — sections + starting page numbers
//   3. Body — KPI grid + each section as a titled compact table
//   4. Footer + page numbers on every body page (cover has no numbering)
import fs from 'node:fs';
import path from 'node:path';
import { PDFDocument, PDFFont, PDFPage, StandardFonts, rgb } from 'pdf-lib';
import fontkit from '@pdf-lib/fontkit';
import type { ReportBundle } from './types';
import { REPORT_META } from './types';

// A4 portrait
const PAGE_W = 595.28;
const PAGE_H = 841.89;
const MARGIN = 44;
const BODY_TOP = PAGE_H - 40;
const BODY_BOTTOM = 60; // leave room for footer

// Nexus palette — light mode
const PRIMARY = rgb(0x01 / 255, 0x69 / 255, 0x6f / 255);
const PRIMARY_DARK = rgb(0x0c / 255, 0x4e / 255, 0x54 / 255);
const TEXT = rgb(0x28 / 255, 0x25 / 255, 0x1d / 255);
const MUTED = rgb(0x7a / 255, 0x79 / 255, 0x74 / 255);
const FAINT = rgb(0xba / 255, 0xb9 / 255, 0xb4 / 255);
const BORDER = rgb(0xd4 / 255, 0xd1 / 255, 0xca / 255);
const SURFACE = rgb(0xf9 / 255, 0xf8 / 255, 0xf5 / 255);
const SURFACE_ALT = rgb(0xfb / 255, 0xfb / 255, 0xf9 / 255);
const WHITE = rgb(1, 1, 1);

const FONT_DIR = path.join(process.cwd(), 'src/lib/reports/assets/fonts');
const IBM_DIR = path.join(process.cwd(), 'src/lib/exports/fonts');

function readFontSafe(...tryPaths: string[]): Uint8Array | null {
  for (const p of tryPaths) {
    try {
      return fs.readFileSync(p);
    } catch {
      // continue
    }
  }
  return null;
}

type Fonts = { reg: PDFFont; bold: PDFFont; ar: PDFFont; arBold: PDFFont };

async function embedFonts(doc: PDFDocument): Promise<Fonts> {
  doc.registerFontkit(fontkit);
  const reg = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const arBytes = readFontSafe(
    path.join(FONT_DIR, 'frutiger-arabic-regular.ttf'),
    path.join(IBM_DIR, 'ibm-plex-sans-arabic-400.ttf')
  );
  const arBoldBytes = readFontSafe(
    path.join(FONT_DIR, 'frutiger-arabic-bold.ttf'),
    path.join(IBM_DIR, 'ibm-plex-sans-arabic-700.ttf')
  );
  const ar = arBytes ? await doc.embedFont(arBytes, { subset: true }) : reg;
  const arBold = arBoldBytes ? await doc.embedFont(arBoldBytes, { subset: true }) : bold;
  return { reg, bold, ar, arBold };
}

// Detect Arabic runs so we pick the right font (fontkit handles shaping).
const HAS_ARABIC = /[\u0600-\u06FF\u0750-\u077F\u08A0-\u08FF\uFB50-\uFDFF\uFE70-\uFEFF]/;
function pickFont(text: string, fonts: Fonts, bold = false): PDFFont {
  if (HAS_ARABIC.test(text)) return bold ? fonts.arBold : fonts.ar;
  return bold ? fonts.bold : fonts.reg;
}

function fitText(text: string, font: PDFFont, size: number, maxWidth: number): string {
  if (!text) return '';
  if (font.widthOfTextAtSize(text, size) <= maxWidth) return text;
  // Use ASCII '...' — the Unicode ellipsis '…' (U+2026) is NOT in Helvetica's
  // WinAnsi encoding and pdf-lib throws when we try to draw it with a standard
  // font. Latin text uses Helvetica, so we stick to ASCII here.
  const ellipsis = '...';
  let lo = 0;
  let hi = text.length;
  while (lo < hi) {
    const mid = Math.floor((lo + hi + 1) / 2);
    const cand = text.slice(0, mid) + ellipsis;
    if (font.widthOfTextAtSize(cand, size) <= maxWidth) lo = mid;
    else hi = mid - 1;
  }
  return text.slice(0, lo) + ellipsis;
}

type Ctx = {
  doc: PDFDocument;
  page: PDFPage;
  fonts: Fonts;
  y: number;
  locale: 'ar' | 'en';
  // page indices where each section starts (populated during body render)
  sectionPages: number[];
  bodyStartPageIndex: number; // index at which body pages begin (skip cover + TOC)
};

function currentPageIndex(ctx: Ctx): number {
  return ctx.doc.getPageIndices().length - 1;
}

function newPage(ctx: Ctx) {
  ctx.page = ctx.doc.addPage([PAGE_W, PAGE_H]);
  ctx.y = BODY_TOP;
}

function ensureSpace(ctx: Ctx, needed: number) {
  if (ctx.y - needed < BODY_BOTTOM) newPage(ctx);
}

function drawText(
  ctx: Ctx,
  text: string,
  x: number,
  y: number,
  opts: { size?: number; bold?: boolean; color?: ReturnType<typeof rgb> } = {}
) {
  const size = opts.size ?? 10;
  const font = pickFont(text, ctx.fonts, !!opts.bold);
  ctx.page.drawText(text, {
    x,
    y,
    size,
    font,
    color: opts.color ?? TEXT,
  });
}

// Right-align helper for RTL layouts.
function drawTextRight(
  ctx: Ctx,
  text: string,
  rightX: number,
  y: number,
  opts: { size?: number; bold?: boolean; color?: ReturnType<typeof rgb> } = {}
) {
  const size = opts.size ?? 10;
  const font = pickFont(text, ctx.fonts, !!opts.bold);
  const w = font.widthOfTextAtSize(text, size);
  ctx.page.drawText(text, {
    x: rightX - w,
    y,
    size,
    font,
    color: opts.color ?? TEXT,
  });
}

// ────────────────────────────────────────────────────────────────────────────
// Cover page
function drawCover(ctx: Ctx, bundle: ReportBundle) {
  const meta = REPORT_META[bundle.type];
  const title = ctx.locale === 'ar' ? meta.name_ar : meta.name_en;
  const desc = ctx.locale === 'ar' ? meta.desc_ar : meta.desc_en;

  // Top brand block (full-bleed)
  ctx.page.drawRectangle({
    x: 0,
    y: PAGE_H - 220,
    width: PAGE_W,
    height: 220,
    color: PRIMARY,
  });
  // Thin darker band under the block for depth
  ctx.page.drawRectangle({
    x: 0,
    y: PAGE_H - 226,
    width: PAGE_W,
    height: 6,
    color: PRIMARY_DARK,
  });

  const brandName =
    ctx.locale === 'ar' ? 'منصة الابتكار للأثر' : 'Innovation-to-Impact Platform';
  const brandFont = pickFont(brandName, ctx.fonts, true);
  ctx.page.drawText(brandName, {
    x: MARGIN,
    y: PAGE_H - 60,
    size: 12,
    font: brandFont,
    color: rgb(0.9, 0.97, 0.96),
  });

  // Rule under brand
  ctx.page.drawLine({
    start: { x: MARGIN, y: PAGE_H - 74 },
    end: { x: MARGIN + 40, y: PAGE_H - 74 },
    thickness: 2,
    color: WHITE,
  });

  const kicker =
    ctx.locale === 'ar' ? 'تقرير رسمي · جاهز للنشر' : 'Official Report · Ready for Distribution';
  ctx.page.drawText(kicker, {
    x: MARGIN,
    y: PAGE_H - 100,
    size: 10,
    font: pickFont(kicker, ctx.fonts, false),
    color: rgb(0.85, 0.94, 0.93),
  });

  // Big title — wrap over up to 3 lines if needed
  const titleFont = pickFont(title, ctx.fonts, true);
  const titleSize = 28;
  const titleMaxWidth = PAGE_W - MARGIN * 2;
  const titleLines = wrap(title, titleFont, titleSize, titleMaxWidth, 3);
  let ty = PAGE_H - 140;
  for (const line of titleLines) {
    ctx.page.drawText(line, {
      x: MARGIN,
      y: ty,
      size: titleSize,
      font: titleFont,
      color: WHITE,
    });
    ty -= titleSize + 4;
  }

  // Description block
  const descFont = pickFont(desc, ctx.fonts, false);
  const descLines = wrap(desc, descFont, 11, PAGE_W - MARGIN * 2, 4);
  let dy = PAGE_H - 260;
  for (const line of descLines) {
    ctx.page.drawText(line, {
      x: MARGIN,
      y: dy,
      size: 11,
      font: descFont,
      color: TEXT,
    });
    dy -= 16;
  }

  // Metadata card (period, generated by, generated on)
  const cardTop = 220;
  const cardH = 150;
  const cardX = MARGIN;
  const cardW = PAGE_W - MARGIN * 2;

  ctx.page.drawRectangle({
    x: cardX,
    y: cardTop,
    width: cardW,
    height: cardH,
    color: SURFACE,
    borderColor: BORDER,
    borderWidth: 0.75,
  });

  // Left accent bar
  ctx.page.drawRectangle({
    x: cardX,
    y: cardTop,
    width: 4,
    height: cardH,
    color: PRIMARY,
  });

  const rangeLabel =
    ctx.locale === 'ar' ? 'الفترة المشمولة بالتقرير' : 'Reporting Period';
  const rangeValue =
    !bundle.dateFrom && !bundle.dateTo
      ? ctx.locale === 'ar'
        ? 'جميع الفترات'
        : 'All Periods'
      : `${bundle.dateFrom ?? '...'}  –  ${bundle.dateTo ?? '...'}`;
  const byLabel = ctx.locale === 'ar' ? 'الجهة المُصدِرة' : 'Prepared By';
  const byValue = bundle.generatedBy || (ctx.locale === 'ar' ? 'إدارة النظام' : 'System Administration');
  const dateLabel = ctx.locale === 'ar' ? 'تاريخ الإصدار' : 'Issued On';
  const dateValue = formatDateTime(bundle.generatedAt, ctx.locale);

  const rows: Array<[string, string]> = [
    [rangeLabel, rangeValue],
    [byLabel, byValue],
    [dateLabel, dateValue],
  ];
  const rowH = (cardH - 20) / rows.length;
  let ry = cardTop + cardH - 20;
  for (const [lbl, val] of rows) {
    drawText(ctx, lbl.toUpperCase(), cardX + 24, ry, {
      size: 8,
      bold: true,
      color: MUTED,
    });
    drawText(ctx, val, cardX + 24, ry - 16, {
      size: 12,
      bold: true,
      color: TEXT,
    });
    // divider
    if (ry - rowH > cardTop + 8) {
      ctx.page.drawLine({
        start: { x: cardX + 24, y: ry - rowH + 8 },
        end: { x: cardX + cardW - 24, y: ry - rowH + 8 },
        thickness: 0.5,
        color: BORDER,
      });
    }
    ry -= rowH;
  }

  // Bottom footer strip (confidential + brand)
  ctx.page.drawLine({
    start: { x: MARGIN, y: 50 },
    end: { x: PAGE_W - MARGIN, y: 50 },
    thickness: 0.5,
    color: BORDER,
  });
  const confidential =
    ctx.locale === 'ar' ? 'وثيقة داخلية · للاستخدام الرسمي' : 'Internal Document · For Official Use';
  drawText(ctx, confidential, MARGIN, 30, { size: 8, color: MUTED });
  const ref =
    ctx.locale === 'ar'
      ? `مرجع: I2I-${bundle.type.toUpperCase()}-${formatDateOnly(bundle.generatedAt)}`
      : `Ref: I2I-${bundle.type.toUpperCase()}-${formatDateOnly(bundle.generatedAt)}`;
  const refFont = pickFont(ref, ctx.fonts, false);
  const refW = refFont.widthOfTextAtSize(ref, 8);
  ctx.page.drawText(ref, {
    x: PAGE_W - MARGIN - refW,
    y: 30,
    size: 8,
    font: refFont,
    color: MUTED,
  });
}

// Naive word-wrap that returns at most maxLines lines. Long lines get ellipsised
// on the last line.
function wrap(text: string, font: PDFFont, size: number, maxWidth: number, maxLines: number): string[] {
  if (!text) return [''];
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let cur = '';
  for (const w of words) {
    const trial = cur ? `${cur} ${w}` : w;
    if (font.widthOfTextAtSize(trial, size) <= maxWidth) {
      cur = trial;
    } else {
      if (cur) lines.push(cur);
      cur = w;
      if (lines.length === maxLines - 1) break;
    }
  }
  if (cur && lines.length < maxLines) lines.push(cur);
  if (lines.length === maxLines) {
    lines[lines.length - 1] = fitText(lines[lines.length - 1] + '...', font, size, maxWidth);
  }
  return lines.length ? lines : [''];
}

function formatDateTime(iso: string, locale: 'ar' | 'en'): string {
  const d = new Date(iso);
  const opts: Intl.DateTimeFormatOptions = {
    year: 'numeric',
    month: 'short',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    timeZone: 'UTC',
  };
  return new Intl.DateTimeFormat(locale === 'ar' ? 'ar-SA' : 'en-GB', opts).format(d) + ' UTC';
}

function formatDateOnly(iso: string): string {
  return iso.slice(0, 10);
}

// ────────────────────────────────────────────────────────────────────────────
// Table of Contents (rendered at the end so page numbers are known, then
// inserted at index 1). We keep this simple and render as a real text page —
// pdf-lib doesn't support internal link anchors trivially, but page numbers
// alone are enough for a printed/emailed report.
function drawToc(page: PDFPage, ctx: Ctx, bundle: ReportBundle) {
  const heading =
    ctx.locale === 'ar' ? 'المحتويات' : 'Table of Contents';
  const headingFont = pickFont(heading, ctx.fonts, true);
  page.drawText(heading, {
    x: MARGIN,
    y: PAGE_H - 90,
    size: 22,
    font: headingFont,
    color: TEXT,
  });
  // Underline
  page.drawRectangle({
    x: MARGIN,
    y: PAGE_H - 100,
    width: 60,
    height: 3,
    color: PRIMARY,
  });

  const meta = REPORT_META[bundle.type];
  const subtitle = ctx.locale === 'ar' ? meta.name_ar : meta.name_en;
  page.drawText(subtitle, {
    x: MARGIN,
    y: PAGE_H - 122,
    size: 11,
    font: pickFont(subtitle, ctx.fonts, false),
    color: MUTED,
  });

  // Entries (KPIs first if present, then sections)
  const entries: Array<{ label: string; page: number }> = [];
  const kpisLabel = ctx.locale === 'ar' ? 'المؤشرات الرئيسية' : 'Key Indicators';
  entries.push({ label: kpisLabel, page: ctx.bodyStartPageIndex + 1 });
  for (let i = 0; i < bundle.sections.length; i++) {
    const s = bundle.sections[i];
    const label = ctx.locale === 'ar' ? s.title_ar : s.title_en;
    // 1-based page number of the section's starting page
    entries.push({ label, page: (ctx.sectionPages[i] ?? ctx.bodyStartPageIndex) + 1 });
  }

  let y = PAGE_H - 160;
  const rowH = 26;
  entries.forEach((e, idx) => {
    const rowY = y;
    // Row background (alt banding)
    if (idx % 2 === 0) {
      page.drawRectangle({
        x: MARGIN,
        y: rowY - 8,
        width: PAGE_W - MARGIN * 2,
        height: rowH - 4,
        color: SURFACE_ALT,
      });
    }
    // Number chip
    const chipLabel = String(idx + 1).padStart(2, '0');
    const chipFont = pickFont(chipLabel, ctx.fonts, true);
    page.drawText(chipLabel, {
      x: MARGIN + 8,
      y: rowY,
      size: 10,
      font: chipFont,
      color: PRIMARY,
    });
    // Label
    const labelFont = pickFont(e.label, ctx.fonts, false);
    const labelSize = 11;
    const labelMaxW = PAGE_W - MARGIN * 2 - 90;
    const shown = fitText(e.label, labelFont, labelSize, labelMaxW);
    page.drawText(shown, {
      x: MARGIN + 40,
      y: rowY,
      size: labelSize,
      font: labelFont,
      color: TEXT,
    });
    // Dot leader + page number (right-aligned)
    const pageStr = String(e.page);
    const pw = ctx.fonts.reg.widthOfTextAtSize(pageStr, 11);
    const pageX = PAGE_W - MARGIN - pw;
    page.drawText(pageStr, {
      x: pageX,
      y: rowY,
      size: 11,
      font: ctx.fonts.reg,
      color: TEXT,
    });
    // dotted leader
    const dotsStart = MARGIN + 40 + labelFont.widthOfTextAtSize(shown, labelSize) + 8;
    const dotsEnd = pageX - 8;
    if (dotsEnd > dotsStart) {
      for (let x = dotsStart; x < dotsEnd; x += 4) {
        page.drawCircle({
          x,
          y: rowY + 3,
          size: 0.6,
          color: FAINT,
        });
      }
    }
    y -= rowH;
  });
}

// ────────────────────────────────────────────────────────────────────────────
// KPIs
function drawKpis(ctx: Ctx, bundle: ReportBundle) {
  if (!bundle.kpis.length) return;

  const sectionLabel = ctx.locale === 'ar' ? 'المؤشرات الرئيسية' : 'Key Indicators';
  ensureSpace(ctx, 30);
  drawText(ctx, sectionLabel, MARGIN, ctx.y - 12, { size: 14, bold: true });
  ctx.page.drawRectangle({
    x: MARGIN,
    y: ctx.y - 20,
    width: 36,
    height: 2.5,
    color: PRIMARY,
  });
  ctx.y -= 32;

  const cardW = (PAGE_W - MARGIN * 2 - 8 * 2) / 3;
  const cardH = 60;
  const rows = Math.ceil(Math.min(bundle.kpis.length, 6) / 3);
  ensureSpace(ctx, rows * (cardH + 8) + 20);
  const startY = ctx.y - cardH;
  bundle.kpis.slice(0, 6).forEach((kpi, i) => {
    const col = i % 3;
    const row = Math.floor(i / 3);
    const x = MARGIN + col * (cardW + 8);
    const y = startY - row * (cardH + 8);
    ctx.page.drawRectangle({
      x,
      y,
      width: cardW,
      height: cardH,
      color: SURFACE,
      borderColor: BORDER,
      borderWidth: 0.5,
    });
    // Left accent
    ctx.page.drawRectangle({
      x,
      y,
      width: 3,
      height: cardH,
      color: PRIMARY,
    });
    const label = ctx.locale === 'ar' ? kpi.label_ar : kpi.label_en;
    const labelFont = pickFont(label, ctx.fonts, false);
    ctx.page.drawText(fitText(label, labelFont, 8.5, cardW - 20), {
      x: x + 12,
      y: y + cardH - 16,
      size: 8.5,
      font: labelFont,
      color: MUTED,
    });
    ctx.page.drawText(kpi.value, {
      x: x + 12,
      y: y + 14,
      size: 20,
      font: pickFont(kpi.value, ctx.fonts, true),
      color: PRIMARY_DARK,
    });
  });
  ctx.y = startY - (rows - 1) * (cardH + 8) - 24;
}

// ────────────────────────────────────────────────────────────────────────────
// Section
function drawSection(
  ctx: Ctx,
  section: ReportBundle['sections'][number],
  sectionIndex: number
) {
  const title = ctx.locale === 'ar' ? section.title_ar : section.title_en;
  ensureSpace(ctx, 48);
  // Record the page this section starts on
  ctx.sectionPages[sectionIndex] = currentPageIndex(ctx);

  // Section header
  drawText(ctx, title, MARGIN, ctx.y - 12, { size: 13, bold: true });
  // Accent underline
  ctx.page.drawRectangle({
    x: MARGIN,
    y: ctx.y - 18,
    width: 32,
    height: 2,
    color: PRIMARY,
  });
  // Right-side row count chip
  const chip = `${section.rows.length} ${ctx.locale === 'ar' ? 'سجل' : 'records'}`;
  drawTextRight(ctx, chip, PAGE_W - MARGIN, ctx.y - 12, {
    size: 9,
    color: MUTED,
  });
  ctx.y -= 26;

  const availableWidth = PAGE_W - MARGIN * 2;
  const totalWeight = section.columns.reduce((acc, c) => acc + (c.width ?? 20), 0);
  const colWidths = section.columns.map((c) => ((c.width ?? 20) / totalWeight) * availableWidth);

  // Header row
  const headerH = 20;
  ensureSpace(ctx, headerH + 4);
  ctx.page.drawRectangle({
    x: MARGIN,
    y: ctx.y - headerH,
    width: availableWidth,
    height: headerH,
    color: PRIMARY,
  });
  let cx = MARGIN;
  for (let i = 0; i < section.columns.length; i++) {
    const c = section.columns[i];
    const label = ctx.locale === 'ar' ? c.label_ar : c.label_en;
    const font = pickFont(label, ctx.fonts, true);
    ctx.page.drawText(fitText(label, font, 8.5, colWidths[i] - 10), {
      x: cx + 7,
      y: ctx.y - 14,
      size: 8.5,
      font,
      color: WHITE,
    });
    cx += colWidths[i];
  }
  ctx.y -= headerH + 2;

  // Empty state
  if (!section.rows.length) {
    const empty = ctx.locale === 'ar' ? 'لا توجد سجلات ضمن هذا النطاق.' : 'No records within the selected range.';
    ctx.page.drawRectangle({
      x: MARGIN,
      y: ctx.y - 24,
      width: availableWidth,
      height: 24,
      color: SURFACE_ALT,
      borderColor: BORDER,
      borderWidth: 0.5,
    });
    drawText(ctx, empty, MARGIN + 12, ctx.y - 15, { size: 9, color: MUTED });
    ctx.y -= 32;
    return;
  }

  // Rows — compact, single-line, alternating band
  const rowH = 16;
  for (let ri = 0; ri < section.rows.length; ri++) {
    const row = section.rows[ri];
    ensureSpace(ctx, rowH);

    // On page break we need to redraw the section header row for continuity.
    if (ctx.y - rowH < BODY_BOTTOM) {
      newPage(ctx);
      // repeat table header
      ctx.page.drawRectangle({
        x: MARGIN,
        y: ctx.y - headerH,
        width: availableWidth,
        height: headerH,
        color: PRIMARY,
      });
      let hx = MARGIN;
      for (let i = 0; i < section.columns.length; i++) {
        const c = section.columns[i];
        const label = ctx.locale === 'ar' ? c.label_ar : c.label_en;
        const font = pickFont(label, ctx.fonts, true);
        ctx.page.drawText(fitText(label, font, 8.5, colWidths[i] - 10), {
          x: hx + 7,
          y: ctx.y - 14,
          size: 8.5,
          font,
          color: WHITE,
        });
        hx += colWidths[i];
      }
      ctx.y -= headerH + 2;
    }

    if (ri % 2 === 1) {
      ctx.page.drawRectangle({
        x: MARGIN,
        y: ctx.y - rowH,
        width: availableWidth,
        height: rowH,
        color: SURFACE,
      });
    }
    // Bottom hairline
    ctx.page.drawLine({
      start: { x: MARGIN, y: ctx.y - rowH },
      end: { x: MARGIN + availableWidth, y: ctx.y - rowH },
      thickness: 0.25,
      color: BORDER,
    });

    let ccx = MARGIN;
    for (let i = 0; i < section.columns.length; i++) {
      const c = section.columns[i];
      const raw = row[c.key];
      const text = raw === null || raw === undefined ? '' : String(raw);
      const font = pickFont(text, ctx.fonts, false);
      ctx.page.drawText(fitText(text, font, 8.5, colWidths[i] - 10), {
        x: ccx + 7,
        y: ctx.y - 11,
        size: 8.5,
        font,
        color: TEXT,
      });
      ccx += colWidths[i];
    }
    ctx.y -= rowH;
  }
  ctx.y -= 18;
}

// ────────────────────────────────────────────────────────────────────────────
// Footer + page numbers — draws on every page after the cover.
function drawFooters(ctx: Ctx, bundle: ReportBundle, coverIndex: number, tocIndex: number | null) {
  const stamp = formatDateTime(bundle.generatedAt, ctx.locale);
  const meta = REPORT_META[bundle.type];
  const title = ctx.locale === 'ar' ? meta.name_ar : meta.name_en;
  const genBy = bundle.generatedBy || (ctx.locale === 'ar' ? 'إدارة النظام' : 'System');
  const rangeLabel =
    !bundle.dateFrom && !bundle.dateTo
      ? ctx.locale === 'ar'
        ? 'جميع الفترات'
        : 'All Periods'
      : `${bundle.dateFrom ?? '...'} – ${bundle.dateTo ?? '...'}`;

  const totalPages = ctx.doc.getPageCount();
  const bodyPageCount = totalPages - (tocIndex === null ? 1 : 2);
  let bodyPageNum = 0;
  for (let i = 0; i < totalPages; i++) {
    if (i === coverIndex) continue; // cover has its own footer
    const isToc = tocIndex !== null && i === tocIndex;
    if (!isToc) bodyPageNum += 1;
    const p = ctx.doc.getPage(i);

    // Top hairline
    p.drawLine({
      start: { x: MARGIN, y: PAGE_H - 20 },
      end: { x: PAGE_W - MARGIN, y: PAGE_H - 20 },
      thickness: 0.4,
      color: BORDER,
    });
    // Header meta (title left, range right)
    const titleFont = pickFont(title, ctx.fonts, true);
    p.drawText(fitText(title, titleFont, 9, PAGE_W / 2), {
      x: MARGIN,
      y: PAGE_H - 32,
      size: 9,
      font: titleFont,
      color: PRIMARY_DARK,
    });
    const rangeFont = pickFont(rangeLabel, ctx.fonts, false);
    const rw = rangeFont.widthOfTextAtSize(rangeLabel, 8.5);
    p.drawText(rangeLabel, {
      x: PAGE_W - MARGIN - rw,
      y: PAGE_H - 32,
      size: 8.5,
      font: rangeFont,
      color: MUTED,
    });

    // Bottom hairline
    p.drawLine({
      start: { x: MARGIN, y: 40 },
      end: { x: PAGE_W - MARGIN, y: 40 },
      thickness: 0.4,
      color: BORDER,
    });

    // Left footer: brand + generatedBy
    const leftFooter =
      ctx.locale === 'ar'
        ? `منصة الابتكار للأثر  ·  ${genBy}`
        : `Innovation-to-Impact  ·  ${genBy}`;
    const leftFont = pickFont(leftFooter, ctx.fonts, false);
    p.drawText(leftFooter, {
      x: MARGIN,
      y: 24,
      size: 8,
      font: leftFont,
      color: MUTED,
    });

    // Center footer: timestamp
    const centerFont = pickFont(stamp, ctx.fonts, false);
    const cw = centerFont.widthOfTextAtSize(stamp, 8);
    p.drawText(stamp, {
      x: (PAGE_W - cw) / 2,
      y: 24,
      size: 8,
      font: centerFont,
      color: MUTED,
    });

    // Right footer: page N of M (body-only numbering)
    if (bodyPageCount > 0 && !isToc) {
      const pageLabel =
        ctx.locale === 'ar'
          ? `صفحة ${bodyPageNum} من ${bodyPageCount}`
          : `Page ${bodyPageNum} of ${bodyPageCount}`;
      const pFont = pickFont(pageLabel, ctx.fonts, false);
      const pw = pFont.widthOfTextAtSize(pageLabel, 8);
      p.drawText(pageLabel, {
        x: PAGE_W - MARGIN - pw,
        y: 24,
        size: 8,
        font: pFont,
        color: MUTED,
      });
    } else if (isToc) {
      const tocLabel = ctx.locale === 'ar' ? 'المحتويات' : 'Contents';
      const tFont = pickFont(tocLabel, ctx.fonts, false);
      const tw = tFont.widthOfTextAtSize(tocLabel, 8);
      p.drawText(tocLabel, {
        x: PAGE_W - MARGIN - tw,
        y: 24,
        size: 8,
        font: tFont,
        color: MUTED,
      });
    }
  }
}

// ────────────────────────────────────────────────────────────────────────────
// Entry point
export async function renderPdf(
  bundle: ReportBundle,
  locale: 'ar' | 'en' = 'en'
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  doc.setTitle(`${REPORT_META[bundle.type].name_en} — I2I`);
  doc.setAuthor('Perplexity Computer');
  doc.setSubject('Innovation-to-Impact Report');
  doc.setCreator('Innovation-to-Impact Reports');
  const fonts = await embedFonts(doc);

  // Cover page
  const cover = doc.addPage([PAGE_W, PAGE_H]);
  const coverIndex = 0;

  // Placeholder TOC page — we'll fill it after body is done so page numbers are known.
  const tocPage = doc.addPage([PAGE_W, PAGE_H]);
  const tocIndex = 1;

  // Body starts here
  const firstBody = doc.addPage([PAGE_W, PAGE_H]);
  const ctx: Ctx = {
    doc,
    page: firstBody,
    fonts,
    y: BODY_TOP,
    locale,
    sectionPages: new Array(bundle.sections.length).fill(-1),
    bodyStartPageIndex: 2,
  };

  drawKpis(ctx, bundle);
  for (let i = 0; i < bundle.sections.length; i++) {
    drawSection(ctx, bundle.sections[i], i);
  }

  // Now that all sections are placed, render the cover and TOC.
  const coverCtx: Ctx = { ...ctx, page: cover };
  drawCover(coverCtx, bundle);
  drawToc(tocPage, ctx, bundle);

  // Finally the shared header/footer strip
  drawFooters(ctx, bundle, coverIndex, tocIndex);
  return doc.save();
}
