begin;
-- Drop the (kind, role) unique constraint if it exists so we can insert role-null rows
alter table innovation.email_templates drop constraint if exists email_templates_kind_role_key;
-- Delete all existing rows (they're test/seed data)
delete from innovation.email_templates;
-- Allow role to be null (role now comes from invitation.role, template is role-agnostic)
alter table innovation.email_templates alter column role drop not null;
-- Add unique constraint on kind only (one template per kind)
create unique index if not exists email_templates_kind_uniq on innovation.email_templates(kind) where role is null;
-- Insert 4 unified templates (role-agnostic, HTML body with {{role_ar}}/{{role_en}} placeholder)
insert into innovation.email_templates (kind, role, subject_ar, subject_en, body_ar, body_en, is_active, is_broadcast)
values
  ('invite',   null, 'دعوتك للانضمام إلى منصة الابتكار', 'You are invited to join the Innovation Platform',   $$<html dir="rtl" lang="ar"><body style="font-family:Tahoma,Arial,sans-serif;background:#F7F6F2;padding:24px;color:#28251D;line-height:1.7"><table role="presentation" width="100%" style="max-width:560px;margin:0 auto;background:#FBFBF9;border:1px solid #D4D1CA;border-radius:12px;padding:32px"><tr><td><h1 style="color:#01696F;margin:0 0 16px 0;font-size:22px">مرحباً {{full_name}}</h1><p style="margin:0 0 12px 0">يسعدنا دعوتك للانضمام إلى منصة الابتكار بصفة <strong>{{role_ar}}</strong> ضمن برنامج <strong>{{program}}</strong>.</p><p style="margin:0 0 20px 0">للبدء بمهامك، يرجى تفعيل حسابك عبر الرابط التالي:</p><p style="margin:24px 0"><a href="{{invite_link}}" style="display:inline-block;background:#01696F;color:#fff;text-decoration:none;padding:12px 24px;border-radius:8px;font-weight:bold">تفعيل الحساب</a></p><p style="margin:20px 0 0 0;color:#7A7974;font-size:13px">هذه الدعوة صالحة حتى: {{expires_at}}</p><p style="margin:8px 0 0 0;color:#7A7974;font-size:13px">إذا لم تكن أنت المقصود بهذه الدعوة، يمكنك تجاهل هذه الرسالة.</p></td></tr></table></body></html>$$,
                     $$<html dir="ltr" lang="en"><body style="font-family:Arial,Helvetica,sans-serif;background:#F7F6F2;padding:24px;color:#28251D;line-height:1.7"><table role="presentation" width="100%" style="max-width:560px;margin:0 auto;background:#FBFBF9;border:1px solid #D4D1CA;border-radius:12px;padding:32px"><tr><td><h1 style="color:#01696F;margin:0 0 16px 0;font-size:22px">Hello {{full_name}}</h1><p style="margin:0 0 12px 0">You are invited to join the Innovation Platform as a <strong>{{role_en}}</strong> in the <strong>{{program}}</strong> program.</p><p style="margin:0 0 20px 0">To get started, please activate your account using the link below:</p><p style="margin:24px 0"><a href="{{invite_link}}" style="display:inline-block;background:#01696F;color:#fff;text-decoration:none;padding:12px 24px;border-radius:8px;font-weight:bold">Activate Account</a></p><p style="margin:20px 0 0 0;color:#7A7974;font-size:13px">This invitation expires on: {{expires_at}}</p><p style="margin:8px 0 0 0;color:#7A7974;font-size:13px">If this invitation was not intended for you, please ignore this email.</p></td></tr></table></body></html>$$,
                     true, false),
  ('accept',   null, 'تأكيد قبول دعوتك', 'Invitation Accepted',
                     $$<html dir="rtl" lang="ar"><body style="font-family:Tahoma,Arial,sans-serif;background:#F7F6F2;padding:24px;color:#28251D;line-height:1.7"><table role="presentation" width="100%" style="max-width:560px;margin:0 auto;background:#FBFBF9;border:1px solid #D4D1CA;border-radius:12px;padding:32px"><tr><td><h1 style="color:#437A22;margin:0 0 16px 0;font-size:22px">أهلاً وسهلاً {{full_name}}</h1><p style="margin:0 0 12px 0">تم قبول دعوتك بصفة <strong>{{role_ar}}</strong> ضمن برنامج <strong>{{program}}</strong>.</p><p style="margin:0 0 20px 0">يمكنك الآن الوصول إلى لوحة أعمالك والبدء بمهامك:</p><p style="margin:24px 0"><a href="{{dashboard_link}}" style="display:inline-block;background:#01696F;color:#fff;text-decoration:none;padding:12px 24px;border-radius:8px;font-weight:bold">الدخول إلى لوحة الأعمال</a></p><p style="margin:20px 0 0 0;color:#7A7974;font-size:13px">في حال احتجت إلى أي مساعدة، فريقنا جاهز لخدمتك.</p></td></tr></table></body></html>$$,
                     $$<html dir="ltr" lang="en"><body style="font-family:Arial,Helvetica,sans-serif;background:#F7F6F2;padding:24px;color:#28251D;line-height:1.7"><table role="presentation" width="100%" style="max-width:560px;margin:0 auto;background:#FBFBF9;border:1px solid #D4D1CA;border-radius:12px;padding:32px"><tr><td><h1 style="color:#437A22;margin:0 0 16px 0;font-size:22px">Welcome {{full_name}}</h1><p style="margin:0 0 12px 0">Your invitation as a <strong>{{role_en}}</strong> in the <strong>{{program}}</strong> program has been accepted.</p><p style="margin:0 0 20px 0">You can now access your dashboard and get started:</p><p style="margin:24px 0"><a href="{{dashboard_link}}" style="display:inline-block;background:#01696F;color:#fff;text-decoration:none;padding:12px 24px;border-radius:8px;font-weight:bold">Go to Dashboard</a></p><p style="margin:20px 0 0 0;color:#7A7974;font-size:13px">If you need any help, our team is here to support you.</p></td></tr></table></body></html>$$,
                     true, false),
  ('reject',   null, 'الرد على دعوتك', 'Regarding Your Invitation',
                     $$<html dir="rtl" lang="ar"><body style="font-family:Tahoma,Arial,sans-serif;background:#F7F6F2;padding:24px;color:#28251D;line-height:1.7"><table role="presentation" width="100%" style="max-width:560px;margin:0 auto;background:#FBFBF9;border:1px solid #D4D1CA;border-radius:12px;padding:32px"><tr><td><h1 style="color:#28251D;margin:0 0 16px 0;font-size:22px">عزيزي/عزيزتي {{full_name}}</h1><p style="margin:0 0 12px 0">شكراً لاهتمامك بالانضمام إلى منصة الابتكار بصفة <strong>{{role_ar}}</strong> ضمن برنامج <strong>{{program}}</strong>.</p><p style="margin:0 0 12px 0">نأسف لإبلاغك أن دعوتك لم تُقبَل في هذه المرة.</p><p style="margin:0 0 20px 0">نقدّر جهودك ونتمنى لك التوفيق في مساعيك المستقبلية، ونرحّب بمشاركتك في فرص أخرى قد تناسبك.</p><p style="margin:20px 0 0 0;color:#7A7974;font-size:13px">لأي استفسار يمكنك التواصل مع فريق المنصة.</p></td></tr></table></body></html>$$,
                     $$<html dir="ltr" lang="en"><body style="font-family:Arial,Helvetica,sans-serif;background:#F7F6F2;padding:24px;color:#28251D;line-height:1.7"><table role="presentation" width="100%" style="max-width:560px;margin:0 auto;background:#FBFBF9;border:1px solid #D4D1CA;border-radius:12px;padding:32px"><tr><td><h1 style="color:#28251D;margin:0 0 16px 0;font-size:22px">Dear {{full_name}}</h1><p style="margin:0 0 12px 0">Thank you for your interest in joining the Innovation Platform as a <strong>{{role_en}}</strong> in the <strong>{{program}}</strong> program.</p><p style="margin:0 0 12px 0">We regret to inform you that your invitation was not accepted at this time.</p><p style="margin:0 0 20px 0">We appreciate your effort and wish you the best in your future endeavors. We welcome your participation in other opportunities that may suit you.</p><p style="margin:20px 0 0 0;color:#7A7974;font-size:13px">For any questions, please contact the platform team.</p></td></tr></table></body></html>$$,
                     true, false),
  ('reminder', null, 'تذكير: دعوتك لا تزال بانتظارك', 'Reminder: Your Invitation is Waiting',
                     $$<html dir="rtl" lang="ar"><body style="font-family:Tahoma,Arial,sans-serif;background:#F7F6F2;padding:24px;color:#28251D;line-height:1.7"><table role="presentation" width="100%" style="max-width:560px;margin:0 auto;background:#FBFBF9;border:1px solid #D4D1CA;border-radius:12px;padding:32px"><tr><td><h1 style="color:#964219;margin:0 0 16px 0;font-size:22px">تذكير — {{full_name}}</h1><p style="margin:0 0 12px 0">نودّ تذكيرك بدعوتك للانضمام إلى منصة الابتكار بصفة <strong>{{role_ar}}</strong> ضمن برنامج <strong>{{program}}</strong>.</p><p style="margin:0 0 20px 0">لم نستلم ردّك حتى الآن. يمكنك تفعيل حسابك بالضغط على الرابط أدناه قبل انتهاء صلاحية الدعوة:</p><p style="margin:24px 0"><a href="{{invite_link}}" style="display:inline-block;background:#01696F;color:#fff;text-decoration:none;padding:12px 24px;border-radius:8px;font-weight:bold">تفعيل الحساب الآن</a></p><p style="margin:20px 0 0 0;color:#7A7974;font-size:13px">تنتهي صلاحية الدعوة في: {{expires_at}}</p></td></tr></table></body></html>$$,
                     $$<html dir="ltr" lang="en"><body style="font-family:Arial,Helvetica,sans-serif;background:#F7F6F2;padding:24px;color:#28251D;line-height:1.7"><table role="presentation" width="100%" style="max-width:560px;margin:0 auto;background:#FBFBF9;border:1px solid #D4D1CA;border-radius:12px;padding:32px"><tr><td><h1 style="color:#964219;margin:0 0 16px 0;font-size:22px">Reminder — {{full_name}}</h1><p style="margin:0 0 12px 0">This is a reminder about your invitation to join the Innovation Platform as a <strong>{{role_en}}</strong> in the <strong>{{program}}</strong> program.</p><p style="margin:0 0 20px 0">We have not received your response yet. Please activate your account using the link below before your invitation expires:</p><p style="margin:24px 0"><a href="{{invite_link}}" style="display:inline-block;background:#01696F;color:#fff;text-decoration:none;padding:12px 24px;border-radius:8px;font-weight:bold">Activate Account Now</a></p><p style="margin:20px 0 0 0;color:#7A7974;font-size:13px">This invitation expires on: {{expires_at}}</p></td></tr></table></body></html>$$,
                     true, false);
commit;
